import AppKit
import Foundation
import AnalyzersKit

/// One self-contained HTML page summarising this Mac's health — the thing
/// you hand to IT, to family, or to a buyer. Everything comes from local
/// logs; nothing leaves the machine unless the user saves and sends it.
enum HealthReport {

    static func save() {
        let panel = NSSavePanel()
        panel.nameFieldStringValue = "Mac-Health-Report-\(dayStamp()).html"
        panel.allowedContentTypes = [.html]
        panel.message = "Save a shareable summary of this Mac's memory, storage and activity."
        guard panel.runModal() == .OK, let url = panel.url else { return }
        let html = build()
        try? html.write(to: url, atomically: true, encoding: .utf8)
        NSWorkspace.shared.activateFileViewerSelecting([url])
    }

    // MARK: - content

    static func build() -> String {
        let trends = TrendsModel.snapshot(period: .day30)
        let disk = LiveStats.diskUsage()
        let runway = ForecastModel.diskRunway()
        let loginRun = LogParser.runs(for: .loginItems).first.map {
            LoginItemsParser.parse(runHeader: $0.header, lines: $0.lines)
        }
        let thermal = (try? String(contentsOf: ThermalWatcher.logURL, encoding: .utf8))?
            .split(separator: "\n").filter { $0.contains("THROTTLE") }.count ?? 0

        var rows = ""
        for offender in trends.offenders.prefix(5) {
            rows += """
            <tr><td>\(escape(offender.name))</td><td class="n">\(offender.count)</td>\
            <td class="n">\(offender.kills)</td></tr>
            """
        }
        if rows.isEmpty { rows = #"<tr><td colspan="3" class="quiet">Nothing repeated — quiet month.</td></tr>"# }

        let diskLine = disk.map {
            "\($0.freeText) free of \($0.totalText)"
                + (runway.map { " · runway \($0.text) at the current pace" } ?? "")
        } ?? "unavailable"

        let loginLine = loginRun.map {
            "\($0.sections.reduce(0) { $0 + $1.entries.count }) startup item(s) audited"
        } ?? "no audit recorded yet"

        return """
        <!doctype html>
        <meta charset="utf-8">
        <title>Mac Health Report — \(dayStamp())</title>
        <style>
          :root { color-scheme: light dark; }
          body { font: 15px/1.55 -apple-system, system-ui, sans-serif; max-width: 46rem;
                 margin: 3rem auto; padding: 0 1.25rem; }
          h1 { font-size: 1.6rem; margin-bottom: .25rem; }
          .sub { opacity: .6; margin-top: 0; }
          .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(9rem, 1fr));
                   gap: .75rem; margin: 1.5rem 0; }
          .card { border: 1px solid color-mix(in srgb, currentColor 15%, transparent);
                  border-radius: .6rem; padding: .8rem .9rem; }
          .card b { display: block; font-size: 1.35rem; font-weight: 650; }
          .card span { opacity: .6; font-size: .82rem; }
          table { border-collapse: collapse; width: 100%; margin-top: .5rem; }
          th, td { text-align: left; padding: .4rem .5rem;
                   border-bottom: 1px solid color-mix(in srgb, currentColor 12%, transparent); }
          td.n, th.n { text-align: right; font-variant-numeric: tabular-nums; }
          .quiet { opacity: .55; }
          footer { margin-top: 2.5rem; font-size: .8rem; opacity: .55; }
        </style>
        <h1>Mac Health Report</h1>
        <p class="sub">\(dayStamp()) · last 30 days · generated locally</p>

        <div class="cards">
          <div class="card"><b>\(trends.kills)</b><span>runaways stopped</span></div>
          <div class="card"><b>\(trends.spikes)</b><span>spikes caught</span></div>
          <div class="card"><b>\(String(format: "%.1f GB", Double(trends.memoryFreedMB) / 1024))</b><span>memory freed</span></div>
          <div class="card"><b>\(ByteSize.format(trends.storageFreedBytes))</b><span>disk reclaimed</span></div>
        </div>

        <h2>Storage</h2>
        <p>\(escape(diskLine))</p>
        <p class="quiet">Reclaimable in the latest dry run: \(ByteSize.format(trends.latestReclaimableBytes))</p>

        <h2>Repeat offenders</h2>
        <table>
          <tr><th>Process</th><th class="n">Events</th><th class="n">Stopped</th></tr>
          \(rows)
        </table>

        <h2>System</h2>
        <p>\(escape(loginLine)) · \(thermal) thermal throttling event(s) recorded</p>

        <footer>Generated by Mac Analyzers — local-only Mac memory and storage care.
        No data left this machine to produce this report.</footer>
        """
    }

    private static func escape(_ s: String) -> String {
        s.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
    }

    private static func dayStamp() -> String {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd"
        f.locale = Locale(identifier: "en_US_POSIX")
        return f.string(from: Date())
    }
}
